### ISSUE TITLE
Find some way to warn people when using wrong barrier dimensions

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_replicant#582] opened 2020-05-22 22:40 UTC
When tile group dimensions don't match barrier dimensions, the simulation hangs but doesn't throw out any errors. This has happened to many times and can confuse a lot of users. Find a way to compare the two values and throw out at least a warning for it.

**Comment by drichmond** [comment] 2020-06-16 01:29
Duplicate of #581

**Closed** 2020-06-16 01:29 UTC
